// Generated by LiveScript 1.2.0
var main;
console.log('hihi');
main = function($scope, $http){
  console.log('blah');
  return $http.get('index.json').success(function(data){
    var ret, c, k, i$, ref$, len$, it, link, obj;
    console.log(data);
    ret = [];
    c = 0;
    for (k in data) {
      console.log(k);
      for (i$ = 0, len$ = (ref$ = data[k].items).length; i$ < len$; ++i$) {
        it = ref$[i$];
        c++;
        link = it.formattedUrl;
        if (!link) {
          continue;
        }
        if (link.search(/g0v\.json$/) >= 0) {
          obj = {
            link: link
          };
          ret.push(obj);
        }
      }
    }
    $scope.links = ret;
    $scope.count = ret.length;
    return $scope.tcount = c;
  });
};