// Generated by LiveScript 1.2.0
var fs, buf, data, k, v, i$, ref$, len$, it, link, ret;
fs = require('fs');
buf = fs.readFileSync('index.json');
data = JSON.parse(buf.toString());
for (k in data) {
  v = data[k];
  for (i$ = 0, len$ = (ref$ = v.items).length; i$ < len$; ++i$) {
    it = ref$[i$];
    if (!(link = it.formattedUrl)) {
      continue;
    }
    ret = /github.com\/[^\/]+\/([^\/]+)\/blob\/master\/g0v.json/.exec(link);
    if (!ret) {
      continue;
    }
    console.log(ret[1]);
    request(req, fn$);
    $http.get("https://api.github.com/repos/g0v/" + ret[1] + "/stats/commit_activity", {
      params: {
        client_id: 'ab2376373fe2da1ccb17',
        client_secret: '6560c859d46e79f00dade30999ee62ca5052437d'
      }
    }).success(fn1$);
  }
}
function fn$(e, r, b){}
function fn1$(d){}