// Generated by LiveScript 1.2.0
var fs, data, hash, user, name, d, obj, res$, i$, ref$, len$, cont;
fs = require('fs');
data = JSON.parse(fs.readFileSync('final.json').toString());
hash = {};
for (user in data) {
  for (name in data[user]) {
    d = data[user][name];
    obj = {};
    res$ = [];
    for (i$ = 0, len$ = (ref$ = d.data).length; i$ < len$; ++i$) {
      cont = ref$[i$];
      res$.push({
        total: cont.total,
        user: cont.author.login
      });
    }
    obj.contributors = res$;
    obj.commits = obj.contributors.reduce(fn$, 0);
    obj.name = d.meta.name_zh || d.meta.name || name;
    obj.homepage = d.meta.homepage;
    obj.repository = ((ref$ = d.meta).repository || (ref$.repository = {})).url || "";
    (hash[user] || (hash[user] = {}))[name] = obj;
  }
}
fs.writeFileSync('simple.json', JSON.stringify(hash));
function fn$(a, b){
  return a + b.total;
}